name: BioGit-R-CMD-check
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'oldrel-1'}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GXPA_TOKEN: ${{ secrets.GXPA_TOKEN }}
      GXPA_USERNAME: ${{ secrets.GXPA_USERNAME }}
      GXPA_PASSWORD: ${{ secrets.GXPA_PASSWORD }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b

      - uses: ./setup-pandoc

      - uses: ./setup-r
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: ./setup-r-dependencies
        with:
          extra-packages: any::rcmdcheck
          needs: check
          dependencies: '"hard"'

      - uses: ./check-r-package
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
